--- #YAML:1.0
name:               WWW-Shorten-ShadyURL
version:            0.02
abstract:           Perl interface to shadyurl.com
author:
    - Jason McManus <infidel AT cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:    0
    WWW::Shorten:  1.90
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
