--- #YAML:1.0
name:                WWW-Shorten-ShadyURL
version:             0.01
abstract:            Perl interface to shadyurl.com
license:             perl
author:              
    - Jason McManus <infidel AT cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
    WWW::Shorten:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
